name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref_name, 'renovate') }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm install
      - run: pnpm lint --fix

      - uses: autofix-ci/action@v1.3.1
        with:
          commit-message: 'style: autofix'
