name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches-ignore:
      - renovate/**

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version-file: .tool-versions

      - run: deno install --allow-scripts
      - run: deno task lint --fix

      - uses: autofix-ci/action@v1.3.1
        with:
          commit-message: 'style: autofix'
