name: 发布更新

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: 发布更新
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version-file: .tool-versions

      - run: bun i
      - run: bun run build -b edge
      - run: bun zip -b edge

      - run: bun submit --edge-zip .output/*-edge.zip
        env:
          EDGE_PRODUCT_ID: ${{ secrets.EDGE_PRODUCT_ID }}
          EDGE_CLIENT_ID: ${{ secrets.EDGE_CLIENT_ID }}
          EDGE_CLIENT_SECRET: ${{ secrets.EDGE_CLIENT_SECRET }}
          EDGE_ACCESS_TOKEN_URL: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}

      - uses: csexton/release-asset-action@3567794e918fa3068116688122a76cdeb57b5f09 # v3
        with:
          pattern: .output/*-edge.zip
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ github.event.release.upload_url }}
