name: 发布更新

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: 发布更新
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version-file: .tool-versions

      - run: deno install --allow-scripts
      - run: deno task build -b edge
      - run: deno task zip -b edge

      - run: deno task submit --edge-zip .output/*-edge.zip
        env:
          EDGE_PRODUCT_ID: ${{ secrets.EDGE_PRODUCT_ID }}
          EDGE_CLIENT_ID: ${{ secrets.EDGE_CLIENT_ID }}
          EDGE_CLIENT_SECRET: ${{ secrets.EDGE_CLIENT_SECRET }}
          EDGE_ACCESS_TOKEN_URL: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}

      - id: get-release
        uses: joutvhu/get-release@9a8271732adc3299a22f8ad09b0a67eb3aa836ac # v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: csexton/release-asset-action@v3
        with:
          pattern: .output/*-edge.zip
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.get-release.outputs.upload_url }}
